
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/XiFengShop
    username: root
    password: 123456

server:
  port: 8888
  servlet:
    context-path: /xifengapp

logging:
  level:
    root: warn

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

